repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
  - repo: local
    hooks:
      - id: swiftlint-autofix-complete
        name: SwiftLint AutoFix Complete
        entry: ./scripts/swiftlint-autofix.sh
        language: system
        types: [swift]
      - id: xcode-quality-check-strict
        name: Xcode Quality Check
        entry: ./scripts/xcode-quality-check.sh # --strict
        language: system
        types: [swift]
        pass_filenames: false
