repos:
#  - repo: https://github.com/pre-commit/pre-commit-hooks
#    rev: v6.0.0
#    hooks:
#    -   id: check-yaml
#    -   id: end-of-file-fixer
#    -   id: trailing-whitespace
#  - repo: https://github.com/realm/SwiftLint
 #   rev: 0.62.1
  #  hooks:
   #   - id: swiftlint
  - repo: local
    hooks:
      - id: swiftlint
        name: SwiftLint
        entry: bash -c 'swiftlint --strict'
        language: system
        types: [swift]
